project_id = "uznzxjjdzjcqremvfqnp"

[auth]
site_url = "https://www.mosaicmahjong.com"
additional_redirect_urls = ["https://mosaicmahjong.com", "https://www.mosaicmahjong.com"]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_confirmations = false
max_frequency = "1m0s"
otp_length = 6

[auth.email.template.magic_link]
subject = "Your Mosaic sign-in code"
content_path = "./supabase/templates/magic_link.html"
